Palabra = input("Ingresar una palabra en mínuscula: ")  #se asigna a una variable la palabra a contar
a="a" # se le asigna a una variable lo que queremos que cuente
e="e"
i="i"
o="o"
u="u"
count_a = Palabra.count(a)  #se cuenta la cantidad de variables que hay dentro de la palabra
count_e = Palabra.count(e)
count_i = Palabra.count(i)
count_o = Palabra.count(o)
count_u = Palabra.count(u)
print("A= "+str(count_a)) #se imprimen la cantidad de veces que se repite cada vocal
print("E= "+str(count_e))
print("I= "+str(count_i))
print("O= "+str(count_o))
print("U= "+str(count_u))