# Generated by Django 4.2.8 on 2023-12-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='nit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='codigo_de_seguridad',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='fecha_de_vencimiento',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='numero_de_tarjeta',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='metodopago',
            name='titular_de_la_tarjeta',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
