# Generated by Django 4.2.8 on 2023-12-24 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='codigo',
            new_name='codigo_de_seguridad',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='vencimiento',
            new_name='fecha_de_vencimiento',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='nombre_titular',
            new_name='nombre_del_titular',
        ),
        migrations.RenameField(
            model_name='metodopago',
            old_name='numero_tarjeta',
            new_name='numero_de_tarjeta',
        ),
    ]
