# Generated by Django 4.2.8 on 2023-12-24 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_codigo_metodopago_codigo_de_seguridad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metodopago',
            old_name='nombre_del_titular',
            new_name='titular_de_la_tarjeta',
        ),
    ]
