# Generated by Django 4.2.8 on 2023-12-26 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_asignacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asignacion',
            new_name='asig',
        ),
    ]
