# Generated by Django 4.2.8 on 2023-12-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_rename_asignacion_asig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asig',
            new_name='asignacion',
        ),
    ]
